/* tslint:disable */
/* eslint-disable */
/**
 * Maya Voice Translator - Validation Dashboard API
 * API for the collaborative validation dashboard for the Maya Voice Translator project. This API manages tasks, corrections, users, and administrative functions for validating linguistic data (transcriptions, translations, dictionary entries).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@mayavoicetranslator.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

