version: '3.8'
services:
  maya-api:
    build: ..
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces/mayavoicetranslator
      # Empêche le conflit node_modules entre host et conteneur
      - /workspaces/mayavoicetranslator/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  web:
    build: ../web
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ../web:/workspaces/mayavoicetranslator/web
      - /workspaces/mayavoicetranslator/web/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U user"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 20s

volumes:
  # Volume persistant pour la base de données
  pgdata:

