# Simple Node.js devcontainer Dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:18

# [Optional] Install additional OS packages
# RUN apt-get update && apt-get install -y <your-package-list>

# [Optional] Set up non-root user, install global npm packages, etc.
# USER node
# RUN npm install -g <your-global-package>

WORKDIR /workspaces
