gantt
    title Despliegue MayaVoiceTranslator
    dateFormat  YYYY-MM
    section Fase piloto
    Formacion y herramientas      :a1, 2025-07, 2m
    Primeros servicios           :a2, after a1, 2m
    section Expansión
    Extension regional           :b1, 2025-11, 18m
    Formacion continua           :b2, after b1, 12m
    section Consolidación
    Autofinanciación             :c1, 2027-05, 12m
    Extension a otros idiomas    :c2, after c1, 12m
